### ISSUE TITLE
make build failed.

### ISSUE THREAD

**Issue by singoo** [edgexfoundry/device-sdk-go#372]
According to the edgexfoundry official website steps , the following error occurs.

The step from => https://docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html#build-your-device-service

![image](https://user-images.githubusercontent.com/29615989/65756327-78601080-e147-11e9-9817-07571d60a1f3.png)

**Comment by wangmingjunabc** [comment]
I have the same problem: 
github.com/edgexfoundry/device-sdk-go/internal/clients/init.go:202:58: cannot use endpoint (type *endpoint.Endpoint) as type clients.Endpointer in argument to metadata.NewAddressableClient:
	*endpoint.Endpoint does not implement clients.Endpointer (missing Fetch method)

**Comment by cloudxxx8** [comment]
Please try to keep our existing go module setting for go-mod-core-contracts. It works fine with v0.1.16, and we haven't updated it. Please make sure the definition in your `go.mod` is as follows
`github.com/edgexfoundry/go-mod-core-contracts v0.1.16`

If you are not using go module, please checkout the v0.1.16 tag in your local go-mod-core-contracts repository
`git checkout v0.1.16`
